### ISSUE TITLE
support for useContext

### ISSUE THREAD

**Issue by arshmeetsr** [betula/use-between#15]
I really appreciate this utility. It would be great if it could support all hooks

**Comment by betula** [comment]
I am very grateful for your use of the library and for the suggested improvement.
But unfortunately, I admit the implementation of the useContext hook is impossible within the useBetween section.

useBetween shared state with logic initializes its state and exists outside the React component tree. React components can use any such state that exists as long as it is used. But this state cannot refer to the useContext hook, since it is executed outside the React component tree.

In the case of useBetween, it is better to use it in conjunction with useContext, but not one inside the other.

You can store some data in the React context and transfer it deep into the React component trees, and some can be shared for the entire application, and then it is convenient to place them in the useBetween.

You can synchronize data from context to a shared state using the useEffect (if strictly necessary).

```javascript
const value = useContext(MyContext);
const { setValue } = useMySharedState();

useEffect(() => {
  setValue(value);
}, [value]);
```
